environment:
  matrix:
  - julia_version: 1.0
  - julia_version: latest

platform:
  - x86
  - x64

# comment the following lines to disallow failures on nightly julia
matrix:
  allow_failures:
  - julia_version: latest

branches:
  only:
    - master
    - /release-.*/

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false

install:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/JuliaCI/Appveyor.jl/master/bin/install.ps1'))

build_script:
  - echo "%JL_BUILD_SCRIPT%"
  - julia -e "%JL_BUILD_SCRIPT%"

test_script:
  - echo "%JL_TEST_SCRIPT%"
  - julia -e "%JL_TEST_SCRIPT%"
